#---
#apiVersion: argoproj.io/v1alpha1
#kind: ApplicationSet
#metadata:
#  name: vh-appset-list-generator
#spec:
#  generators:
#  - list:
#      elements:
#      - path: overlays/my-awesome-app-1/dev
#        name: app-set-my-awesome-app-1
#      - path: overlays/my-awesome-app-2/dev
#        name: app-set-my-awesome-app-2
#      - path: overlays/my-awesome-app-3/dev
#        name: app-set-my-awesome-app-3
#  template:
#    metadata:
#      name: '{{name}}'
#    spec:
#      project: default
#      source:
#        repoURL: https://github.com/mbursac32/argo.git
#        targetRevision: master
#        path: '{{path}}'
#      destination:
#        namespace: argocd
#        name: in-cluster

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vh-appset-git-generator
spec:
  generators:
  - git:
      repoURL: git@bitbucket.org:microblink/net-apps.git
      revision: master
      directories:
      - path: overlays/my-awesome-app-1/dev
      - path: overlays/my-awesome-app-2/dev
      - path: overlays/my-awesome-app-3/dev
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mbursac32/argo.git
        targetRevision: master
        path: '{{path}}'
      destination:
        namespace: argocd
        name: in-cluster
