---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vh-appset
spec:
  generators:
  - list:
      elements:
      - path: overlays/my-awesome-app-1/dev
        name: my-awesome-app-1
      - path: overlays/my-awesome-app-2/dev
        name: my-awesome-app-2
      - path: overlays/my-awesome-app-3/dev
        name: my-awesome-app-3
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mbursac32/argo.git
        targetRevision: master
        path: '{{path}}'
      destination:
        namespace: argocd
        name: in-cluster

