apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-awesome-app-1
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: overlays/my-awesome-app-1/dev
    repoURL: https://github.com/mbursac32/argo-apps.git
    targetRevision: HEAD
    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-awesome-app-2
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: overlays/my-awesome-app-2/dev
    repoURL: https://github.com/mbursac32/argo-apps.git
    targetRevision: HEAD

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-awesome-app-3
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: overlays/my-awesome-app-3/dev
    repoURL: https://github.com/mbursac32/argo-apps.git
    targetRevision: HEAD